complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
filesize_format = "kb"
filesize_metric = true
nonzero_exit_errors = true
pivot_mode = "auto"
plugin_dirs = []
prompt = "starship prompt"
# prompt = "echo 'Î» '"
rm_always_trash = false
skip_welcome_message = true
path = [
     "~/.bin",
     "~/.local/bin",
     "~/.cargo/bin",
     "~/.yarn/bin",
     "~/go/bin",
     "/usr/local/go/bin",
     "/opt/flutter/bin",
     "/opt/android-sdk/cmdline-tools/latest/bin",
     "/home/xiuxiu/.local/share/solana/install/active_release/bin",
]
startup = [ 
    "alias l = ls",
    "alias ll = ls --long",
    "alias la = ls --all",
    "alias lla = ls --long --all",

    "alias dump = col --no-backspaces --spaces",

    "alias update = sudo pacman -Syyu --color auto",
    "alias cleanup = bash -c 'sudo pacman -Rns $(pacman -Qtdq)'",
    "alias upclean = update && cleanup",

    "alias sr = sudo reboot",
    "alias ssn = sudo shutdown now",

    "alias nv = nvim",
    "alias tm = tmux",

    "alias gstatus = git status",
    "alias gadd = git add",
    "alias gcommit = git commit",
    "alias gpush = git push",
    "alias gpull = git pull",
    "alias gfetch = git fetch",

    "alias cupdate = cargo update",
    "alias ccheck = cargo check",
    "alias cbuild = cargo build",
    "alias crelease = cargo build --release",
    "alias crun = cargo run",
    "alias ctest = cargo test",
    "alias cclean = cargo clean",
    "alias cadd = cargo add",
    "alias crm = cargo rm",

    "def nuver [] { version | pivot key value }",
    "def manout [ prog ] { man $prog | dump }",
    "def mansave [ prog ] { man $prog | save $'(build-string $prog '.man')' }",

    "mkdir ~/.cache/starship",
    "starship init nu | save ~/.cache/starship/init.nu",
    "source ~/.cache/starship/init.nu",
]
table_mode = "rounded"

[color_config]
primitive_int = "green"
primitive_decimal = "red"
primitive_filesize = "green"
primitive_string = "pb"
primitive_line = "yellow"
primitive_columnpath = "cyan"
primitive_pattern = "white"
primitive_boolean = "green"
primitive_date = "yd"
primitive_duration = "blue"
primitive_range = "purple"
primitive_path = "blue"
primitive_binary = "cyan"
separator_color = "purple"
header_align = "center" # left|l, right|r, center|c
header_color = "cyan" # green|g, red|r, blue|u, black|b, yellow|y, purple|p, cyan|c, white|w
header_bold = true
index_color = "ri"
leading_trailing_space_bg = "white"

[line_editor]
auto_add_history = true
bell_style = "visible"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "circular"
edit_mode = "nvim"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"
